# Generated by Django 5.0.6 on 2024-06-18 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_client_letter_trymailing'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.client', verbose_name='почты'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.letter', verbose_name='письмо'),
        ),
        migrations.AddField(
            model_name='trymailing',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='рассылка'),
        ),
    ]
