# Generated by Django 5.0.6 on 2024-06-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mailing_email_mailing_letter_trymailing_mailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='body',
            field=models.CharField(max_length=500, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='email',
        ),
        migrations.AddField(
            model_name='mailing',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, to='main.client', verbose_name='почты'),
        ),
    ]
