# Generated by Django 5.0.6 on 2024-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_client_comment_alter_letter_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='job_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='id APSheduler'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='email',
            field=models.ManyToManyField(to='main.client', verbose_name='почты'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_sent',
            field=models.DateTimeField(verbose_name='Дата и время первой отправки'),
        ),
    ]
