# Generated by Django 5.0.6 on 2024-06-27 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_mailing_next_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='job_id',
        ),
    ]
