# Generated by Django 5.0.6 on 2024-06-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mailing_next_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='статус'),
        ),
    ]
