# Generated by Django 5.0.6 on 2024-07-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_client_author_letter_author_mailing_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_status', 'Может активировать/деактивировать рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
